# Classifier SpaCy
Utilisation de textcat dans la pipeline nlp spacy pour tester la classification à partir de sample de 512 tokens de chaque histoire

In [1]:
import pandas as pd

In [3]:
df_cp = pd.read_csv('cp.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'cp.csv'

In [4]:
df = df_cp[df_cp.source.isin(['reddit','fandom'])]
df['texte'] = df.texte.apply(lambda x : x[:1000000])
df_fandom = df[df.source == 'fandom'].sample(2000)
df_reddit= df[df.source == 'reddit'].sample(2000)

df_train = pd.concat([df_fandom,df_reddit])
cats= df_train.source.unique().tolist()

/var/folders/4m/_y65_yfx68b53909_pvhthr40000gn/T/ipykernel_10098/1623927441.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['texte'] = df.texte.apply(lambda x : x[:1000000])

In [ ]:
import spacy
from spacy.tokens import DocBin
from spacy.tokens import Doc, Span
from collections import Counter
from typing import List, Tuple, Set

def make_docs_chunked(
    nlp,
    data: List[Tuple[str, str]],
    target_file: str,
    cats: Set[str],
    max_tokens: int = 512,
    overlap: int = 50
):
    """
    Convertit des textes longs en chunks sans perdre les embeddings,
    gr�ce � span.as_doc(). Ajoute les labels pour textcat.
    """
    docs = DocBin(store_user_data=True)
    class_counter = Counter()

    for text, label in data:
        # DOC ORIGINAL AVEC EMBEDDINGS
        doc = nlp(text)
        n_tokens = len(doc)

        start = 0
        while start < n_tokens:
            end = min(start + max_tokens, n_tokens)

            # Le chunk : Span \u2192 Doc (garde les vecteurs !)
            chunk_span = doc[start:end]
            chunk_doc = chunk_span.as_doc()

            # Ajouter les labels (binary exclusive)
            for cat in cats:
                chunk_doc.cats[cat] = 1 if cat == label else 0

            docs.add(chunk_doc)
            class_counter[label] += 1

            if end == n_tokens: 
                break

            start = end - overlap  # overlap token-based

    docs.to_disk(target_file)

    print(f"\u2714 DocBin saved: {target_file}")
    print(f"\U0001f4ca Distribution des chunks par classe : {dict(class_counter)}")

    return docs

In [ ]:
data = list(zip(df_train['texte'],df_train['source']))

In [ ]:
import os
import shutil
import spacy
from spacy.tokens import DocBin
from spacy.cli.train import train as spacy_train
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
import numpy as np
from tqdm import tqdm
import pandas as pd
import logging

# ======================================================
# LOGGING GLOBAL
# ======================================================

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s \u2014 %(levelname)s \u2014 %(message)s",
    datefmt="%H:%M:%S"
)

logger = logging.getLogger(__name__)
logger.info("\U0001f680 Démarrage de la pipeline de cross-validation spaCy + chunking")


# ======================================================
# 1. Pr�paration des donn�es : chunking
# ======================================================

logger.info("\U0001f4cc Étape 1 : Préparation des données & chunking")

# Exemple : data = [(text, label), ...]
# \U0001f449 � adapter � ton dataset r�el
# data = list(zip(df["texte"], df["label"]))

logger.info(f"Taille du dataset brut : {len(data)} exemples")

cats = set(label for _, label in data)
logger.info(f"Classes détectées : {cats}")

# Mod�le Spacy minimal
nlp_raw = spacy.load('en_core_web_sm')
logger.info("Modèle tokenizer chargé : en_core_web_sm")

# Construction du fichier ALL.SPACY
logger.info("\u23f3 Génération des chunks\u2026")

make_docs_chunked(
    nlp=nlp_raw,
    data=data,
    target_file="spacy_textcat/all.spacy",
    cats=cats,
    max_tokens=512,
    overlap=50
)

logger.info("\u2714 Chunking termin�")

# ======================================================
# 2. Charger les chunks
# ======================================================

logger.info("\U0001f4cc Étape 2 : Chargement des chunks")

alldocs = DocBin().from_disk("spacy_textcat/all.spacy")
docs = list(alldocs.get_docs(nlp_raw.vocab))

logger.info(f"Nombre total de chunks chargés : {len(docs)}")


# ======================================================
# 3. R�cup�rer les labels
# ======================================================

logger.info("\U0001f4cc Étape 3 : Extraction des labels pour la stratification")

nlp_tmp = spacy.load("output_spacy/spacy_textcat_update/model-best")
labels = list(nlp_tmp.get_pipe("textcat").labels)

logger.info(f"Labels dans le modèle : {labels}")

y_all = []
for doc in docs:
    y_all.append(labels[np.argmax([doc.cats[l] for l in labels])])

logger.info(f"Répartition des labels (chunks) : {pd.Series(y_all).value_counts().to_dict()}")


# ======================================================
# 4. Cross-validation stratifi�e
# ======================================================

logger.info("\U0001f4cc Étape 4 : Cross-validation stratifiée")

k = 5
kf = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)
reports = []

for fold, (train_idx, dev_idx) in enumerate(kf.split(docs, y_all)):

    logger.info(f"\n===== \U0001f501 FOLD {fold+1}/{k} =====")

    fold_dir = f"cv/fold_{fold}"
    os.makedirs(fold_dir, exist_ok=True)

    logger.info(f"\U0001f4c2 Dossier créé : {fold_dir}")
    logger.info(f"Taille train : {len(train_idx)} \u2014 Taille dev : {len(dev_idx)}")

    # -------------------------
    # TRAIN/DEV .spacy
    # -------------------------
    db_train = DocBin()
    db_dev = DocBin()

    for i in train_idx:
        db_train.add(docs[i])
    for i in dev_idx:
        db_dev.add(docs[i])

    db_train.to_disk(f"{fold_dir}/train.spacy")
    db_dev.to_disk(f"{fold_dir}/dev.spacy")

    logger.info("\U0001f4be train.spacy & dev.spacy écrits")

    # -------------------------
    # Copier config.cfg
    # -------------------------
    shutil.copy("/home/alexandrelionnet/Documents/phd/script/spacy_textcat/config_cpu.cfg", f"{fold_dir}/config.cfg")
    logger.info("\U0001f4c4 config.cfg copié dans le dossier du fold")

    # -------------------------
    # Entra�nement via spacy_train
    # -------------------------
    logger.info("\u23f3 Entraînement du modèle\u2026")

    spacy_train(
        f"{fold_dir}/config.cfg",
        output_path=f"{fold_dir}/model",
        overrides={
            "paths.train": f"{fold_dir}/train.spacy",
            "paths.dev": f"{fold_dir}/dev.spacy",
        },
    )

    logger.info("\u2714 Entraînement terminé pour ce fold")

    # -------------------------
    # �VALUATION
    # -------------------------
    logger.info("\u23f3 Évaluation du modèle\u2026")

    nlp_fold = spacy.load(f"{fold_dir}/model/model-best")

    y_true = []
    y_pred = []

    for doc in tqdm([docs[i] for i in dev_idx], desc=f"Fold {fold} eval"):
        gold = doc.cats
        pred = nlp_fold(doc.text).cats

        true_label = labels[np.argmax([gold[l] for l in labels])]
        pred_label = labels[np.argmax([pred[l] for l in labels])]

        y_true.append(true_label)
        y_pred.append(pred_label)

    report = classification_report(
        y_true, y_pred, target_names=labels, output_dict=True, zero_division=0
    )
    reports.append(report)

    logger.info(f"\U0001f4ca Rapport pour le fold {fold+1} ajout�")

# ======================================================
# 5. Moyenne finale des folds
# ======================================================

logger.info("\U0001f4cc Étape 5 : Moyenne finale sur les folds")

results_df = pd.DataFrame(reports)
mean_results = results_df.mean(numeric_only=True)

logger.info("\n===== MOYENNE DES FOLDS =====")
logger.info(mean_results.to_string())

print("\n===== MOYENNE DES FOLDS =====")
print(mean_results)

In [ ]:
# Aplatir les colonnes contenant des dictionnaires
df_flat = results_df.applymap(
    lambda d: d['precision'] if isinstance(d, dict) else d
).add_prefix('precision_')

df_flat['recall_fandom'] = results_df['fandom'].apply(lambda d: d['recall'])
df_flat['f1_fandom'] = results_df['fandom'].apply(lambda d: d['f1-score'])

df_flat['recall_reddit'] = results_df['reddit'].apply(lambda d: d['recall'])
df_flat['f1_reddit'] = results_df['reddit'].apply(lambda d: d['f1-score'])

df_flat['precision_macro'] = results_df['macro avg'].apply(lambda d: d['precision'])
df_flat['recall_macro']    = results_df['macro avg'].apply(lambda d: d['recall'])
df_flat['f1_macro']        = results_df['macro avg'].apply(lambda d: d['f1-score'])

df_flat['precision_weighted'] = results_df['weighted avg'].apply(lambda d: d['precision'])
df_flat['recall_weighted']    = results_df['weighted avg'].apply(lambda d: d['recall'])
df_flat['f1_weighted']        = results_df['weighted avg'].apply(lambda d: d['f1-score'])

df_flat

# Régression logisitque : une autre approche 
En réutilisant la méthode utilisée pour le cas canon / non_canon, Application d'un logit sur les features formelles et thématique.

In [29]:
import pandas as pd 
df = pd.read_csv('/Users/rolly/Documents/10-19_Université_et_scolarité/PhD/script/output/data_pronoms.csv')
df = df[df.source.isin(['fandom','reddit'])]

## if reddit == 0 , if fandom ==1
df.source= df.source.apply(lambda x : 1 if x=='fandom' else 0)

num_features=['longueur_texte', 'nombre_mots',
       'longueur_phrase', 'Flesch Reading Ease', 'Flesch-Kincaid Grade Level',
       'Gunning Fog Index', 'SMOG Index', 'Automated Readability Index',
       'Coleman-Liau Index', 'Dale-Chall Readability Score', 'Indice Lix',
       'Ratio Types/Tokens', 'Hapax Legomena', 'Densité Lexicale',
       "Indice Honore's R", 'fear', 'neutral', 'disgust', 'anger', 'sadness',
       'surprise', 'joy', 'noun_verb_ratio', 'noun_adj_verb_ratio',
       'passive_verb_ratio', 'nll','Ratio_P1_rest']
df= df[num_features + ['source']]

/var/folders/4m/_y65_yfx68b53909_pvhthr40000gn/T/ipykernel_9581/228725182.py:2: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/rolly/Documents/10-19_Université_et_scolarité/PhD/script/output/data_pronoms.csv')

In [31]:
# ==============================================
# PIPELINE LOGIT ROBUSTE + MÉTRIQUES CLASSIQUES
# ==============================================

import numpy as np
import pandas as pd
import statsmodels.api as sm

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score

print("=== 1. Nettoyage des données ===")

df_clean = df.copy()

# Filtrage textes trop courts
df_clean = df_clean[df_clean["nombre_mots"] > 30]

# Gestion inf / NaN
df_clean = df_clean.replace([np.inf, -np.inf], np.nan)
df_clean = df_clean.dropna()

print("Shape après nettoyage :", df_clean.shape)

# --------------------------------------
# Winsorisation 1%-99%
# --------------------------------------

def winsorize_series(s, lower=0.01, upper=0.99):
    return s.clip(s.quantile(lower), s.quantile(upper))

num_cols = df_clean.select_dtypes(include=np.number).columns
num_cols = num_cols.drop("source")

for col in num_cols:
    df_clean[col] = winsorize_series(df_clean[col])

print("Winsorisation effectuée.")

# --------------------------------------
# Log-transform variables heavy-tailed
# --------------------------------------

heavy_cols = [
    "longueur_texte",
    "nombre_mots",
    "Hapax Legomena",
    "Indice Honore's R",
    "Indice Lix"
]

for col in heavy_cols:
    if col in df_clean.columns:
        df_clean[f"log_{col}"] = np.log1p(df_clean[col])

print("Log-transform effectuée.")

# --------------------------------------
# Séparation X / y
# --------------------------------------

y = df_clean["source"]
X = df_clean.drop(columns=["source"])

print("\n=== 2. Sélection L1 avec validation croisée ===")

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegressionCV(
        penalty="l1",
        solver="saga",
        cv=cv,
        scoring="roc_auc",
        max_iter=5000,
        n_jobs=-1,
        random_state=42
    ))
])

pipeline.fit(X, y)

# Performance AUC
y_pred = pipeline.predict_proba(X)[:, 1]
auc = roc_auc_score(y, y_pred)

print("AUC (cross-validated) :", round(auc, 4))

# Variables sélectionnées
coefs = pd.Series(
    pipeline.named_steps["model"].coef_[0],
    index=X.columns
)

selected_vars = coefs[coefs != 0].index.tolist()

print("\nVariables sélectionnées :", len(selected_vars))
print(selected_vars)

# --------------------------------------
# 3. Refit Logit classique statsmodels
# --------------------------------------

print("\n=== 3. Refit Logit classique (statsmodels) ===")

X_selected = X[selected_vars]
X_selected = sm.add_constant(X_selected)

logit_model = sm.Logit(y, X_selected)
result = logit_model.fit(disp=0)

print(result.summary())

# --------------------------------------
# 4. Métriques classiques
# --------------------------------------

print("\n=== 4. Métriques classiques ===")

llf = result.llf          # log-likelihood modèle
llnull = result.llnull    # log-likelihood modèle nul
llr = result.llr          # likelihood ratio test
llr_pvalue = result.llr_pvalue
pseudo_r2 = result.prsquared
aic = result.aic
bic = result.bic

print(f"Log-Likelihood (model)      : {llf:.3f}")
print(f"Log-Likelihood (null model) : {llnull:.3f}")
print(f"LLR statistic               : {llr:.3f}")
print(f"LLR p-value                 : {llr_pvalue:.5f}")
print(f"Pseudo R² (McFadden)        : {pseudo_r2:.4f}")
print(f"AIC                         : {aic:.2f}")
print(f"BIC                         : {bic:.2f}")

# --------------------------------------
# 5. Odds ratios
# --------------------------------------

print("\n=== 5. Odds Ratios ===")

odds_ratios = np.exp(result.params)
conf = result.conf_int()
conf_odds = np.exp(conf)

odds_table = pd.DataFrame({
    "Odds Ratio": odds_ratios,
    "CI Lower": conf_odds[0],
    "CI Upper": conf_odds[1],
    "p-value": result.pvalues
})

print(odds_table.sort_values("Odds Ratio", ascending=False))

=== 1. Nettoyage des données ===
Shape après nettoyage : (24868, 28)
Winsorisation effectuée.
Log-transform effectuée.

=== 2. Sélection L1 avec validation croisée ===
AUC (cross-validated) : 0.7968

Variables sélectionnées : 32
['longueur_texte', 'nombre_mots', 'longueur_phrase', 'Flesch Reading Ease', 'Flesch-Kincaid Grade Level', 'Gunning Fog Index', 'SMOG Index', 'Automated Readability Index', 'Coleman-Liau Index', 'Dale-Chall Readability Score', 'Indice Lix', 'Ratio Types/Tokens', 'Hapax Legomena', 'Densité Lexicale', "Indice Honore's R", 'fear', 'neutral', 'disgust', 'anger', 'sadness', 'surprise', 'joy', 'noun_verb_ratio', 'noun_adj_verb_ratio', 'passive_verb_ratio', 'nll', 'Ratio_P1_rest', 'log_longueur_texte', 'log_nombre_mots', 'log_Hapax Legomena', "log_Indice Honore's R", 'log_Indice Lix']

=== 3. Refit Logit classique (statsmodels) ===
                           Logit Regression Results
==============================================================================
Dep. Variable:                 source   No. Observations:                24868
Model:                          Logit   Df Residuals:                    24835
Method:                           MLE   Df Model:                           32
Date:                Mon, 02 Mar 2026   Pseudo R-squ.:                  0.2139
Time:                        14:56:33   Log-Likelihood:                -13463.
converged:                       True   LL-Null:                       -17128.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                            9.9541     11.299      0.881      0.378     -12.192      32.100
longueur_texte                  -0.0005   4.89e-05    -10.326      0.000      -0.001      -0.000
nombre_mots                      0.0032      0.000     12.161      0.000       0.003       0.004
longueur_phrase                  0.0650      0.022      3.021      0.003       0.023       0.107
Flesch Reading Ease              0.0719      0.022      3.313      0.001       0.029       0.114
Flesch-Kincaid Grade Level       0.4591      0.156      2.952      0.003       0.154       0.764
Gunning Fog Index                0.5961      0.077      7.754      0.000       0.445       0.747
SMOG Index                      -0.0978      0.044     -2.200      0.028      -0.185      -0.011
Automated Readability Index     -1.1446      0.062    -18.539      0.000      -1.266      -1.024
Coleman-Liau Index               0.3581      0.048      7.514      0.000       0.265       0.452
Dale-Chall Readability Score    -1.0922      0.077    -14.197      0.000      -1.243      -0.941
Indice Lix                       0.3814      0.031     12.330      0.000       0.321       0.442
Ratio Types/Tokens             -13.7330      0.859    -15.990      0.000     -15.416     -12.050
Hapax Legomena                   0.0020      0.001      3.446      0.001       0.001       0.003
Densité Lexicale                 9.8569      0.794     12.413      0.000       8.301      11.413
Indice Honore's R                0.0022      0.001      2.980      0.003       0.001       0.004
fear                            -2.2406      0.457     -4.906      0.000      -3.136      -1.345
neutral                         -2.9944      0.477     -6.279      0.000      -3.929      -2.060
disgust                         -0.3293      0.467     -0.706      0.480      -1.244       0.585
anger                           -0.8318      0.505     -1.649      0.099      -1.821       0.157
sadness                         -0.8748      0.505     -1.732      0.083      -1.865       0.115
surprise                         0.0134      0.494      0.027      0.978      -0.954       0.981
joy                             -0.4270      0.742     -0.576      0.565      -1.881       1.027
noun_verb_ratio                 -3.1368      0.266    -11.791      0.000      -3.658      -2.615
noun_adj_verb_ratio              2.2730      0.200     11.368      0.000       1.881       2.665
passive_verb_ratio               3.3732      0.752      4.483      0.000       1.898       4.848
nll                              0.1369      0.065      2.114      0.035       0.010       0.264
Ratio_P1_rest                   -3.0830      0.091    -33.700      0.000      -3.262      -2.904
log_longueur_texte              17.9188      0.919     19.493      0.000      16.117      19.721
log_nombre_mots                -19.6866      0.912    -21.586      0.000     -21.474     -17.899
log_Hapax Legomena               0.6598      0.437      1.510      0.131      -0.197       1.516
log_Indice Honore's R           -2.3665      1.633     -1.449      0.147      -5.567       0.834
log_Indice Lix                  -6.8970      0.948     -7.275      0.000      -8.755      -5.039
================================================================================================

=== 4. Métriques classiques ===
Log-Likelihood (model)      : -13463.431
Log-Likelihood (null model) : -17127.681
LLR statistic               : 7328.502
LLR p-value                 : 0.00000
Pseudo R² (McFadden)        : 0.2139
AIC                         : 26992.86
BIC                         : 27260.87

=== 5. Odds Ratios ===
                                Odds Ratio      CI Lower      CI Upper  \
log_longueur_texte            6.054130e+07  9.990235e+06  3.668831e+08
const                         2.103772e+04  5.071578e-06  8.726781e+13
Densité Lexicale              1.908959e+04  4.025962e+03  9.051562e+04
passive_verb_ratio            2.917103e+01  6.674624e+00  1.274901e+02
noun_adj_verb_ratio           9.708350e+00  6.560684e+00  1.436619e+01
log_Hapax Legomena            1.934327e+00  8.214209e-01  4.555059e+00
Gunning Fog Index             1.814965e+00  1.561103e+00  2.110109e+00
Flesch-Kincaid Grade Level    1.582696e+00  1.166884e+00  2.146681e+00
Indice Lix                    1.464364e+00  1.378217e+00  1.555895e+00
Coleman-Liau Index            1.430619e+00  1.303038e+00  1.570691e+00
nll                           1.146766e+00  1.010020e+00  1.302026e+00
Flesch Reading Ease           1.074512e+00  1.029792e+00  1.121175e+00
longueur_phrase               1.067201e+00  1.023104e+00  1.113199e+00
surprise                      1.013476e+00  3.852377e-01  2.666234e+00
nombre_mots                   1.003179e+00  1.002666e+00  1.003692e+00
Indice Honore's R             1.002174e+00  1.000744e+00  1.003606e+00
Hapax Legomena                1.002026e+00  1.000873e+00  1.003180e+00
longueur_texte                9.994950e-01  9.993992e-01  9.995909e-01
SMOG Index                    9.067992e-01  8.311147e-01  9.893758e-01
disgust                       7.194131e-01  2.882191e-01  1.795701e+00
joy                           6.524834e-01  1.524424e-01  2.792756e+00
anger                         4.352503e-01  1.618943e-01  1.170164e+00
sadness                       4.169338e-01  1.548884e-01  1.122316e+00
Dale-Chall Readability Score  3.354815e-01  2.885250e-01  3.900802e-01
Automated Readability Index   3.183387e-01  2.820554e-01  3.592894e-01
fear                          1.063961e-01  4.346987e-02  2.604132e-01
log_Indice Honore's R         9.380981e-02  3.822696e-03  2.302114e+00
neutral                       5.006840e-02  1.966345e-02  1.274875e-01
Ratio_P1_rest                 4.582061e-02  3.829918e-02  5.481916e-02
noun_verb_ratio               4.342276e-02  2.577911e-02  7.314201e-02
log_Indice Lix                1.010763e-03  1.576430e-04  6.480730e-03
Ratio Types/Tokens            1.086009e-06  2.017357e-07  5.846342e-06
log_nombre_mots               2.819721e-09  4.719682e-10  1.684610e-08

                                    p-value
log_longueur_texte             1.267129e-84
const                          3.783408e-01
Densité Lexicale               2.224731e-35
passive_verb_ratio             7.371980e-06
noun_adj_verb_ratio            6.044395e-30
log_Hapax Legomena             1.310967e-01
Gunning Fog Index              8.929280e-15
Flesch-Kincaid Grade Level     3.152899e-03
Indice Lix                     6.239769e-35
Coleman-Liau Index             5.732977e-14
nll                            3.452689e-02
Flesch Reading Ease            9.214346e-04
longueur_phrase                2.520816e-03
surprise                       9.783610e-01
nombre_mots                    5.003288e-34
Indice Honore's R              2.880157e-03
Hapax Legomena                 5.681941e-04
longueur_texte                 5.402238e-25
SMOG Index                     2.779501e-02
disgust                        4.804154e-01
joy                            5.649212e-01
anger                          9.924290e-02
sadness                        8.335165e-02
Dale-Chall Readability Score   9.606670e-46
Automated Readability Index    1.000120e-76
fear                           9.289763e-07
log_Indice Honore's R          1.472527e-01
neutral                        3.400155e-10
Ratio_P1_rest                 5.770733e-249
noun_verb_ratio                4.352890e-32
log_Indice Lix                 3.462965e-13
Ratio Types/Tokens             1.498646e-57
log_nombre_mots               2.416872e-103

In [ ]:
##pinguin

import numpy as np
import pingouin as pg
import pandas as pd 

df = pd.read_csv("/Users/rolly/Documents/10-19_Université_et_scolarité/PhD/script/output/data_pronoms.csv")

/var/folders/4m/_y65_yfx68b53909_pvhthr40000gn/T/ipykernel_9581/2936433463.py:7: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/Users/rolly/Documents/10-19_Université_et_scolarité/PhD/script/output/data_pronoms.csv")

In [3]:
df_res = pd.DataFrame()
metrics = ['longueur_texte', 'nombre_mots',
       'longueur_phrase', 'Flesch Reading Ease', 'Flesch-Kincaid Grade Level',
       'Gunning Fog Index', 'SMOG Index', 'Automated Readability Index',
       'Coleman-Liau Index', 'Dale-Chall Readability Score', 'Indice Lix',
       'Ratio Types/Tokens', 'Hapax Legomena', 'Densité Lexicale',
       "Indice Honore's R", 'fear', 'neutral', 'disgust', 'anger', 'sadness',
       'surprise', 'joy', 'noun_verb_ratio', 'noun_adj_verb_ratio',
       'passive_verb_ratio','Ratio_P1_rest']
for metric in metrics :
    x = df[df.source == 'fandom'][metric].dropna()
    y= df[df.source == 'reddit'][metric].dropna()
    

    res = pg.ttest(x,y)
    res['metrics']= metric
    df_res = pd.concat([df_res,res])

df_res.set_index('metrics')

/var/folders/4m/_y65_yfx68b53909_pvhthr40000gn/T/ipykernel_9581/2454407455.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_res = pd.concat([df_res,res])
/var/folders/4m/_y65_yfx68b53909_pvhthr40000gn/T/ipykernel_9581/2454407455.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_res = pd.concat([df_res,res])
/var/folders/4m/_y65_yfx68b53909_pvhthr40000gn/T/ipykernel_9581/2454407455.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_res = pd.concat([df_res,res])
/var/folders/4m/_y65_yfx68b53909_pvhthr40000gn/T/ipykernel_9581/2454407455.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_res = pd.concat([df_res,res])
/var/folders/4m/_y65_yfx68b53909_pvhthr40000gn/T/ipykernel_9581/2454407455.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_res = pd.concat([df_res,res])

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
metrics,,,,,,,,
longueur_texte,10.957803,12344.300623,two-sided,8.187318e-28,"[2488.72, 3573.07]",0.150892,1.419e+24,1.000000
nombre_mots,10.427667,12372.566187,two-sided,2.361111e-25,"[417.38, 610.62]",0.143557,5.045e+21,1.000000
longueur_phrase,0.042949,24187.646718,two-sided,9.657422e-01,"[-0.24, 0.25]",0.000546,0.014,0.050211
Flesch Reading Ease,-10.013286,24755.984938,two-sided,1.477469e-23,"[-2.02, -1.36]",0.126271,7.452e+19,NaN
Flesch-Kincaid Grade Level,3.250042,24932.829174,two-sided,1.155408e-03,"[0.07, 0.3]",0.040498,2.806,0.890201
Gunning Fog Index,2.773435,24916.446470,two-sided,5.550908e-03,"[0.05, 0.27]",0.034538,0.669,0.775922
SMOG Index,12.936889,19784.207758,two-sided,3.979230e-38,"[0.2, 0.27]",0.169487,2.271e+34,NaN
Automated Readability Index,5.317945,24953.961450,two-sided,1.058486e-07,"[0.24, 0.53]",0.066331,1.951e+04,0.999445
Coleman-Liau Index,28.611400,20059.696408,two-sided,1.680695e-176,"[0.57, 0.65]",0.374228,9.337e+172,1.000000
Dale-Chall Readability Score,15.762134,19918.292979,two-sided,1.229846e-55,"[0.17, 0.22]",0.206336,6.421e+51,1.000000
Indice Lix,9.856076,23649.681285,two-sided,7.141635e-23,"[1.13, 1.69]",0.120813,1.574e+19,1.000000
Ratio Types/Tokens,-13.894229,12653.443408,two-sided,1.433982e-43,"[-0.02, -0.01]",0.190832,7.777e+39,NaN
Hapax Legomena,14.730879,16896.517470,two-sided,8.200213e-49,"[39.87, 52.11]",0.196361,1.112e+45,NaN
Densité Lexicale,30.099984,18374.497670,two-sided,2.469268e-194,"[0.01, 0.02]",0.397645,2.023e+191,1.000000
Indice Honore's R,25.960869,18847.344296,two-sided,5.017823e-146,"[101.55, 118.14]",0.342002,3.07e+142,1.000000
fear,-32.083406,23854.300765,two-sided,3.742624e-221,"[-0.1, -0.09]",0.409011,1.194e+217,1.000000
neutral,4.406974,21834.014589,two-sided,1.053241e-05,"[0.0, 0.01]",0.057021,234.135,0.994266
disgust,27.935591,22000.521505,two-sided,8.669390e-169,"[0.06, 0.06]",0.361064,8.575e+164,1.000000
anger,10.933796,21592.964536,two-sided,9.395166e-28,"[0.01, 0.02]",0.141686,1.093e+24,NaN
sadness,12.504096,18494.837112,two-sided,9.889733e-36,"[0.01, 0.02]",0.165071,9.594e+31,1.000000
surprise,-1.359769,23811.883340,two-sided,1.739160e-01,"[-0.0, 0.0]",0.017341,0.036,0.276352
joy,3.288921,21635.933151,two-sided,1.007327e-03,"[0.0, 0.0]",0.042608,3.186,0.918292
noun_verb_ratio,22.126609,19083.806250,two-sided,3.890663e-107,"[0.08, 0.09]",0.291083,2.403e+103,1.000000
noun_adj_verb_ratio,24.419335,19139.343723,two-sided,1.024642e-129,"[0.12, 0.14]",0.321139,1.12e+126,1.000000
passive_verb_ratio,20.883455,17960.683095,two-sided,1.037216e-95,"[0.01, 0.01]",0.276571,9.72e+91,1.000000
Ratio_P1_rest,-55.852546,17053.973825,two-sided,0.000000e+00,"[-0.16, -0.15]",0.746467,inf,1.000000

In [32]:
df_res

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power,metrics
T-test,10.957803,12344.300623,two-sided,8.187318e-28,"[2488.72, 3573.07]",0.150892,1.419e+24,1.000000,longueur_texte
T-test,10.427667,12372.566187,two-sided,2.361111e-25,"[417.38, 610.62]",0.143557,5.045e+21,1.000000,nombre_mots
T-test,0.042949,24187.646718,two-sided,9.657422e-01,"[-0.24, 0.25]",0.000546,0.014,0.050211,longueur_phrase
T-test,-10.013286,24755.984938,two-sided,1.477469e-23,"[-2.02, -1.36]",0.126271,7.452e+19,NaN,Flesch Reading Ease
T-test,3.250042,24932.829174,two-sided,1.155408e-03,"[0.07, 0.3]",0.040498,2.806,0.890201,Flesch-Kincaid Grade Level
T-test,2.773435,24916.446470,two-sided,5.550908e-03,"[0.05, 0.27]",0.034538,0.669,0.775922,Gunning Fog Index
T-test,12.936889,19784.207758,two-sided,3.979230e-38,"[0.2, 0.27]",0.169487,2.271e+34,NaN,SMOG Index
T-test,5.317945,24953.961450,two-sided,1.058486e-07,"[0.24, 0.53]",0.066331,1.951e+04,0.999445,Automated Readability Index
T-test,28.611400,20059.696408,two-sided,1.680695e-176,"[0.57, 0.65]",0.374228,9.337e+172,1.000000,Coleman-Liau Index
T-test,15.762134,19918.292979,two-sided,1.229846e-55,"[0.17, 0.22]",0.206336,6.421e+51,1.000000,Dale-Chall Readability Score
T-test,9.856076,23649.681285,two-sided,7.141635e-23,"[1.13, 1.69]",0.120813,1.574e+19,1.000000,Indice Lix
T-test,-13.894229,12653.443408,two-sided,1.433982e-43,"[-0.02, -0.01]",0.190832,7.777e+39,NaN,Ratio Types/Tokens
T-test,14.730879,16896.517470,two-sided,8.200213e-49,"[39.87, 52.11]",0.196361,1.112e+45,NaN,Hapax Legomena
T-test,30.099984,18374.497670,two-sided,2.469268e-194,"[0.01, 0.02]",0.397645,2.023e+191,1.000000,Densité Lexicale
T-test,25.960869,18847.344296,two-sided,5.017823e-146,"[101.55, 118.14]",0.342002,3.07e+142,1.000000,Indice Honore's R
T-test,-32.083406,23854.300765,two-sided,3.742624e-221,"[-0.1, -0.09]",0.409011,1.194e+217,1.000000,fear
T-test,4.406974,21834.014589,two-sided,1.053241e-05,"[0.0, 0.01]",0.057021,234.135,0.994266,neutral
T-test,27.935591,22000.521505,two-sided,8.669390e-169,"[0.06, 0.06]",0.361064,8.575e+164,1.000000,disgust
T-test,10.933796,21592.964536,two-sided,9.395166e-28,"[0.01, 0.02]",0.141686,1.093e+24,NaN,anger
T-test,12.504096,18494.837112,two-sided,9.889733e-36,"[0.01, 0.02]",0.165071,9.594e+31,1.000000,sadness
T-test,-1.359769,23811.883340,two-sided,1.739160e-01,"[-0.0, 0.0]",0.017341,0.036,0.276352,surprise
T-test,3.288921,21635.933151,two-sided,1.007327e-03,"[0.0, 0.0]",0.042608,3.186,0.918292,joy
T-test,22.126609,19083.806250,two-sided,3.890663e-107,"[0.08, 0.09]",0.291083,2.403e+103,1.000000,noun_verb_ratio
T-test,24.419335,19139.343723,two-sided,1.024642e-129,"[0.12, 0.14]",0.321139,1.12e+126,1.000000,noun_adj_verb_ratio
T-test,20.883455,17960.683095,two-sided,1.037216e-95,"[0.01, 0.01]",0.276571,9.72e+91,1.000000,passive_verb_ratio
T-test,-55.852546,17053.973825,two-sided,0.000000e+00,"[-0.16, -0.15]",0.746467,inf,1.000000,Ratio_P1_rest